#include "LCARSHTMLGenerator.h"
#include "Misc/FileHelper.h"
#include "Misc/DateTime.h"

FString FLCARSHTMLGenerator::GenerateHTML(const FReportData& Data)
{
	FString HTML = TEXT(R"(<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>)");
	
	HTML += Data.Title + TEXT(R"(</title>
    <style>
)");
	HTML += GenerateCSS();
	HTML += TEXT(R"(
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <header class="lcars-header">
            <div class="header-title">
                <h1>LCARS TEST REPORT</h1>
                <p class="subtitle">STARFLEET AUTOMATED QUALITY ASSURANCE SYSTEM</p>
            </div>
            <div class="header-stats">
                <div class="timestamp">)");
	
	HTML += Data.Timestamp.ToString(TEXT("%Y-%m-%d %H:%M:%S"));
	HTML += TEXT(R"(</div>
            </div>
        </header>

)");
	
	HTML += GenerateTestSummarySection(Data);
	HTML += GenerateAPIMetricsSection(Data);
	HTML += GeneratePerformanceMetricsSection(Data);
	HTML += GenerateTestDetailsSection(Data);
	
	HTML += TEXT(R"(
        <!-- Footer -->
        <footer class="lcars-footer">
            <p>Generated by: <strong>Nexus Orchestration Engine</strong> | Palantír Subsystem</p>
            <p>Framework: NexusQA v1.0 | © 2025</p>
        </footer>
    </div>

    <script>
)");
	HTML += GenerateJavaScript();
	HTML += TEXT(R"(
    </script>
</body>
</html>
)");

	return HTML;
}

bool FLCARSHTMLGenerator::SaveToFile(const FReportData& Data, const FString& OutputPath)
{
	FString HTML = GenerateHTML(Data);
	return FFileHelper::SaveStringToFile(HTML, *OutputPath);
}

FString FLCARSHTMLGenerator::GenerateCSS()
{
	// LCARS-inspired styling (condensed but maintains Star Trek aesthetic for recruiter appeal)
	return TEXT(R"(
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Courier New', monospace; background: linear-gradient(135deg, #000033 0%, #001155 100%); color: #ffcc00; padding: 20px; min-height: 100vh; }
        .container { max-width: 1400px; margin: 0 auto; }
        .lcars-header { background: #000033; border: 3px solid #ff9900; border-radius: 15px; padding: 25px; margin-bottom: 25px; }
        .header-title h1 { color: #ff9900; font-size: 2.5em; letter-spacing: 2px; text-shadow: 0 0 15px #ff9900; }
        .subtitle { color: #ffcc00; font-size: 1.1em; margin-top: 8px; }
        .timestamp { color: #99ccff; font-size: 1em; margin-top: 10px; }
        .summary-section, .api-section, .performance-section, .details-section { background: #001133; border-left: 8px solid #ff9900; padding: 25px; margin-bottom: 25px; border-radius: 8px; }
        .api-section { border-left-color: #00ccff; }
        .performance-section { border-left-color: #ff00ff; }
        .details-section { border-left-color: #ffcc00; }
        h2 { color: #ff9900; font-size: 1.8em; margin-bottom: 15px; text-transform: uppercase; }
        .api-section h2 { color: #00ccff; }
        .performance-section h2 { color: #ff00ff; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 18px; margin: 18px 0; }
        .stat-card { background: #000022; border: 2px solid #ffcc00; border-radius: 8px; padding: 18px; text-align: center; }
        .stat-card.passed { border-color: #00ff00; }
        .stat-card.failed { border-color: #ff0000; }
        .stat-label { font-size: 0.85em; color: #99ccff; margin-bottom: 8px; text-transform: uppercase; }
        .stat-value { font-size: 2.5em; font-weight: bold; color: #ffcc00; }
        .stat-card.passed .stat-value { color: #00ff00; }
        .stat-card.failed .stat-value { color: #ff0000; }
        .pass-rate { font-size: 1.1em; margin-top: 8px; color: #ffffff; }
        .chart-container { background: #000022; border: 2px solid #ffcc00; border-radius: 8px; padding: 18px; margin: 18px 0; }
        .chart-title { color: #ff9900; font-size: 1.3em; margin-bottom: 12px; text-align: center; }
        .endpoint-list { list-style: none; padding: 0; }
        .endpoint-item { background: #000033; border-left: 4px solid #00ff00; padding: 12px; margin: 8px 0; border-radius: 4px; display: flex; justify-content: space-between; }
        .endpoint-item.failed { border-left-color: #ff0000; }
        .endpoint-name { color: #ffffff; font-size: 1em; }
        .endpoint-time { color: #00ccff; font-size: 1.1em; font-weight: bold; }
        .status-code-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 12px; margin-top: 15px; }
        .status-code-item { background: #000033; border: 2px solid #ffcc00; border-radius: 6px; padding: 12px; text-align: center; }
        .status-code-item.success { border-color: #00ff00; }
        .status-code-item.error { border-color: #ff0000; }
        .status-code { font-size: 1.8em; font-weight: bold; color: #ffcc00; }
        .status-code-item.success .status-code { color: #00ff00; }
        .status-code-item.error .status-code { color: #ff0000; }
        .status-count { font-size: 1.3em; color: #ffffff; margin-top: 4px; }
        .test-item { background: #000022; border: 2px solid #ffcc00; border-radius: 6px; padding: 18px; margin: 12px 0; }
        .test-item.passed { border-color: #00ff00; }
        .test-item.failed { border-color: #ff0000; }
        .test-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
        .test-name { color: #ffffff; font-size: 1.2em; font-weight: bold; }
        .test-status { padding: 6px 16px; border-radius: 15px; font-weight: bold; font-size: 1em; }
        .test-status.PASSED { background: #00ff00; color: #000000; }
        .test-status.FAILED { background: #ff0000; color: #ffffff; }
        .test-meta { color: #99ccff; font-size: 0.85em; margin-top: 8px; }
        .test-error { background: #330000; border-left: 4px solid #ff0000; padding: 12px; margin-top: 8px; border-radius: 4px; color: #ffcccc; font-size: 0.9em; }
        .test-artifacts { margin-top: 12px; }
        .artifact-link { display: inline-block; background: #000033; border: 1px solid #00ccff; color: #00ccff; padding: 4px 12px; border-radius: 4px; margin: 4px; text-decoration: none; font-size: 0.85em; }
        .artifact-link:hover { background: #00ccff; color: #000033; }
        .lcars-footer { text-align: center; padding: 25px; color: #99ccff; font-size: 0.85em; }
        .lcars-footer p { margin: 4px 0; }
        @media (max-width: 768px) { .header-title h1 { font-size: 1.8em; } .stats-grid { grid-template-columns: 1fr; } }
    )");
}

FString FLCARSHTMLGenerator::GenerateJavaScript()
{
	// No JS needed - keep it simple and fast
	return TEXT(R"(
        console.log('LCARS Report loaded successfully');
    )");
}

FString FLCARSHTMLGenerator::GenerateTestSummarySection(const FReportData& Data)
{
	float PassRate = Data.TotalTests > 0 ? (float)Data.PassedTests / Data.TotalTests * 100.0f : 0.0f;
	// Clamp PassRate to valid range [0, 100]
	PassRate = FMath::Clamp(PassRate, 0.0f, 100.0f);
	
	FString HTML = TEXT(R"(
        <!-- Summary Section -->
        <section class="summary-section">
            <h2>[ Executive Summary ]</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-label">TOTAL TESTS</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.TotalTests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card passed">
                    <div class="stat-label">PASSED</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.PassedTests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card failed">
                    <div class="stat-label">FAILED</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.FailedTests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">PASS RATE</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.1f%%"), PassRate);
	HTML += TEXT(R"(</div>
                </div>
            </div>
            <div class="stats-grid" style="margin-top: 20px;">
                <div class="stat-card">
                    <div class="stat-label">TOTAL RUNTIME</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.2fs"), Data.TotalDuration);
	HTML += TEXT(R"(</div>
                </div>
            </div>
        </section>
)");
	
	return HTML;
}

FString FLCARSHTMLGenerator::GenerateAPIMetricsSection(const FReportData& Data)
{
	if (Data.APIMetrics.TotalRequests == 0)
	{
		return TEXT("");
	}
	
	float APISuccessRate = Data.APIMetrics.TotalRequests > 0 ? 
		(float)Data.APIMetrics.SuccessfulRequests / Data.APIMetrics.TotalRequests * 100.0f : 0.0f;
	
	FString HTML = TEXT(R"(
        <!-- API Metrics Section -->
        <section class="api-section">
            <h2>[ API Testing Metrics ]</h2>
            
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-label">TOTAL REQUESTS</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.APIMetrics.TotalRequests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card passed">
                    <div class="stat-label">SUCCESSFUL</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.APIMetrics.SuccessfulRequests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card failed">
                    <div class="stat-label">FAILED</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.APIMetrics.FailedRequests);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">AVG RESPONSE TIME</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.1fms"), Data.APIMetrics.AvgResponseTimeMs);
	HTML += TEXT(R"(</div>
                    <div class="pass-rate">Success Rate: )");
	HTML += FString::Printf(TEXT("%.1f%%"), APISuccessRate);
	HTML += TEXT(R"(</div>
                </div>
            </div>
            
            <!-- Status Code Distribution -->
            <div class="chart-container">
                <h3 class="chart-title">HTTP Status Code Distribution</h3>
                <div class="status-code-grid">
)");
	
	for (const auto& Pair : Data.APIMetrics.StatusCodeDistribution)
	{
		int32 StatusCode = Pair.Key;
		int32 Count = Pair.Value;
		FString StatusClass = (StatusCode >= 200 && StatusCode < 300) ? TEXT("success") : TEXT("error");
		
		HTML += TEXT(R"(                    <div class="status-code-item )");
		HTML += StatusClass;
		HTML += TEXT(R"(">
                        <div class="status-code">");
		HTML += FString::FromInt(StatusCode);
		HTML += TEXT(R"(</div>
                        <div class="status-count">&times; )");
		HTML += FString::FromInt(Count);
		HTML += TEXT(R"(</div>
                    </div>
)");
	}
	
	HTML += TEXT(R"(                </div>
            </div>
            
            <!-- Endpoint Response Times -->
            <div class="chart-container">
                <h3 class="chart-title">Endpoint Response Times</h3>
                <ul class="endpoint-list">
)");
	
	for (const auto& Pair : Data.APIMetrics.EndpointResponseTimes)
	{
		const FString& Endpoint = Pair.Key;
		float ResponseTime = Pair.Value;
		FString StatusClass = ResponseTime < 500.0f ? TEXT("") : TEXT("failed");
		
		HTML += TEXT(R"(                    <li class="endpoint-item )");
		HTML += StatusClass;
		HTML += TEXT(R"(">
                        <span class="endpoint-name">)");
		HTML += Endpoint;
		HTML += TEXT(R"(</span>
                        <span class="endpoint-time">)");
		HTML += FString::Printf(TEXT("%.1f ms"), ResponseTime);
		HTML += TEXT(R"(</span>
                    </li>
)");
	}
	
	HTML += TEXT(R"(                </ul>
            </div>
        </section>
)");
	
	return HTML;
}

FString FLCARSHTMLGenerator::GeneratePerformanceMetricsSection(const FReportData& Data)
{
	if (Data.PerfMetrics.AvgFPS == 0.0f)
	{
		return TEXT("");
	}
	
	FString HTML = TEXT(R"(
        <!-- Performance Metrics Section -->
        <section class="performance-section">
            <h2>[ Performance Metrics ]</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-label">AVERAGE FPS</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.1f"), Data.PerfMetrics.AvgFPS);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">MIN / MAX FPS</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.1f / %.1f"), Data.PerfMetrics.MinFPS, Data.PerfMetrics.MaxFPS);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">PEAK MEMORY</div>
                    <div class="stat-value">)");
	HTML += FString::Printf(TEXT("%.1f MB"), Data.PerfMetrics.PeakMemoryMB);
	HTML += TEXT(R"(</div>
                </div>
                <div class="stat-card">
                    <div class="stat-label">HITCHES DETECTED</div>
                    <div class="stat-value">)");
	HTML += FString::FromInt(Data.PerfMetrics.HitchCount);
	HTML += TEXT(R"(</div>
                </div>
            </div>
        </section>
)");
	
	return HTML;
}

FString FLCARSHTMLGenerator::GenerateTestDetailsSection(const FReportData& Data)
{
	FString HTML = TEXT(R"(
        <!-- Test Details Section -->
        <section class="details-section">
            <h2>[ Test Results ]</h2>
)");
	
	for (const FTestResult& Test : Data.Tests)
	{
		FString StatusClass = Test.Status;
		
		HTML += TEXT(R"(            <div class="test-item )");
		HTML += StatusClass.ToLower();
		HTML += TEXT(R"(">
                <div class="test-header">
                    <span class="test-name">)");
		HTML += Test.Name;
		HTML += TEXT(R"(</span>
                    <span class="test-status )");
		HTML += Test.Status;
		HTML += TEXT(R"(">)");
		HTML += Test.Status;
		HTML += TEXT(R"(</span>
                </div>
                <div class="test-meta">
                    Duration: )");
		HTML += FString::Printf(TEXT("%.3fs"), Test.DurationSeconds);
		
		if (!Test.TraceID.IsEmpty())
		{
			HTML += TEXT(" | Trace ID: ");
			HTML += Test.TraceID;
		}
		
		HTML += TEXT(R"(</div>
)");
		
		if (!Test.ErrorMessage.IsEmpty())
		{
			HTML += TEXT(R"(                <div class="test-error">
                    [ERROR] )");
			HTML += Test.ErrorMessage;
			HTML += TEXT(R"(
                </div>
)");
		}
		
		if (Test.Artifacts.Num() > 0)
		{
			HTML += TEXT(R"(                <div class="test-artifacts">
                    <strong>Artifacts:</strong>
)");
			for (const FString& Artifact : Test.Artifacts)
			{
				HTML += TEXT(R"(                    <a href=")");
				HTML += Artifact;
				HTML += TEXT(R"(" class="artifact-link">📎 )");
				HTML += FPaths::GetCleanFilename(Artifact);
				HTML += TEXT(R"(</a>
)");
			}
			HTML += TEXT(R"(                </div>
)");
		}
		
		HTML += TEXT(R"(            </div>
)");
	}
	
	HTML += TEXT(R"(        </section>
)");
	
	return HTML;
}
